apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-world
  revisionHistoryLimit: 5
  progressDeadlinesSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-pod
        image: nigelpoulton/k8sbook:1.0
        ports:
        - containerPort: 8080

# revisionHistoryLimit: tells kubernetes how many older versions/replicasets to keep.
# Keeping more give more rollback options (but don`t keep too many, because this can bloat the object)
# progressDeadlinesSeconds: tells kubernetes how long to wait during a rollout for each new replica to come online.
# In this case, each new replica has 5 minutes to come up before kubernetes considers the rollout stalled.
# strategy: how to update the pods when a rollout occurs